// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";

function add(a, b) {
  return a + b | 0;
}

console.log(84);

function $$double(x) {
  return (x << 1);
}

function fact(n) {
  if (n !== 1) {
    return Caml_int32.imul(n, fact(n - 1 | 0));
  } else {
    return 1;
  }
}

function fact_t(n) {
  var _n = n;
  var _acc = 1;
  while(true) {
    var acc = _acc;
    var n$1 = _n;
    if (n$1 !== 1) {
      _acc = Caml_int32.imul(acc, n$1);
      _n = n$1 - 1 | 0;
      continue ;
      
    } else {
      return acc;
    }
  };
}

var answer = 42;

export {
  answer   ,
  add      ,
  $$double ,
  fact     ,
  fact_t   ,
  
}
/*  Not a pure module */
