// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

import * as Curry from "bs-platform/lib/es6/curry.js";

function everySecond(what) {
  var iid = setInterval(what, 1000);
  return (function () {
      clearInterval(iid);
      return /* () */0;
    });
}

function repeat(what, _times) {
  while(true) {
    var times = _times;
    if (times !== 0) {
      Curry._1(what, /* () */0);
      _times = times - 1 | 0;
      continue ;
      
    } else {
      return /* () */0;
    }
  };
}

function sayHello() {
  console.log("Hello");
  return /* () */0;
}

function sayHelloTimes(param) {
  return repeat(sayHello, param);
}

sayHelloTimes(10);

var unsub = everySecond(sayHello);

setTimeout(unsub, 10000);

export {
  everySecond   ,
  repeat        ,
  sayHello      ,
  sayHelloTimes ,
  unsub         ,
  
}
/*  Not a pure module */
